// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExecuteAutomation.Reqnroll.Dynamics.Specs.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AsyncSupportFeature : object, Xunit.IClassFixture<AsyncSupportFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "AsyncSupport", "Testing asynchronous operations with dynamic tables", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AsyncSupport.feature"
#line hidden
        
        public AsyncSupportFeature(AsyncSupportFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create dynamic instance asynchronously")]
        [Xunit.TraitAttribute("FeatureTitle", "AsyncSupport")]
        [Xunit.TraitAttribute("Description", "Create dynamic instance asynchronously")]
        public async System.Threading.Tasks.Task CreateDynamicInstanceAsynchronously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create dynamic instance asynchronously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Age",
                            "Email"});
                table1.AddRow(new string[] {
                            "John",
                            "30",
                            "john@example.com"});
#line 6
        await testRunner.GivenAsync("I have a table for async processing", ((string)(null)), table1, "Given ");
#line hidden
#line 9
        await testRunner.WhenAsync("I create a dynamic instance asynchronously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
        await testRunner.ThenAsync("the async dynamic instance should have property Name with value John", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
        await testRunner.AndAsync("the async dynamic instance should have property Email with value john@example.com" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create dynamic set asynchronously")]
        [Xunit.TraitAttribute("FeatureTitle", "AsyncSupport")]
        [Xunit.TraitAttribute("Description", "Create dynamic set asynchronously")]
        public async System.Threading.Tasks.Task CreateDynamicSetAsynchronously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create dynamic set asynchronously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Age",
                            "Status"});
                table2.AddRow(new string[] {
                            "John",
                            "30",
                            "Active"});
                table2.AddRow(new string[] {
                            "Alice",
                            "25",
                            "Inactive"});
                table2.AddRow(new string[] {
                            "Bob",
                            "40",
                            "Active"});
#line 14
        await testRunner.GivenAsync("I have a table with multiple rows for async processing", ((string)(null)), table2, "Given ");
#line hidden
#line 19
        await testRunner.WhenAsync("I create a dynamic set asynchronously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
        await testRunner.ThenAsync("the async dynamic set should have 3 items", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
        await testRunner.AndAsync("the first item in the set should have Name John", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filter table rows asynchronously")]
        [Xunit.TraitAttribute("FeatureTitle", "AsyncSupport")]
        [Xunit.TraitAttribute("Description", "Filter table rows asynchronously")]
        public async System.Threading.Tasks.Task FilterTableRowsAsynchronously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter table rows asynchronously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Age",
                            "Status"});
                table3.AddRow(new string[] {
                            "John",
                            "30",
                            "Active"});
                table3.AddRow(new string[] {
                            "Alice",
                            "25",
                            "Inactive"});
                table3.AddRow(new string[] {
                            "Bob",
                            "40",
                            "Active"});
                table3.AddRow(new string[] {
                            "Claire",
                            "35",
                            "Active"});
#line 24
        await testRunner.GivenAsync("I have a table with various statuses", ((string)(null)), table3, "Given ");
#line hidden
#line 30
        await testRunner.WhenAsync("I filter the rows asynchronously where Status is Active", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
        await testRunner.ThenAsync("the async filtered table should have 3 rows", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
        await testRunner.AndAsync("all rows in the filtered table should have Status Active", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Project table columns asynchronously")]
        [Xunit.TraitAttribute("FeatureTitle", "AsyncSupport")]
        [Xunit.TraitAttribute("Description", "Project table columns asynchronously")]
        public async System.Threading.Tasks.Task ProjectTableColumnsAsynchronously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Project table columns asynchronously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Age",
                            "Email",
                            "Phone"});
                table4.AddRow(new string[] {
                            "John",
                            "Doe",
                            "30",
                            "john@example.com",
                            "123-456-7890"});
                table4.AddRow(new string[] {
                            "Alice",
                            "Smith",
                            "25",
                            "alice@example.com",
                            "234-567-8901"});
#line 35
        await testRunner.GivenAsync("I have a table with multiple columns for async projection", ((string)(null)), table4, "Given ");
#line hidden
#line 39
        await testRunner.WhenAsync("I select only the FirstName and Email columns asynchronously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
        await testRunner.ThenAsync("the async projected table should have 2 columns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
        await testRunner.AndAsync("the projected columns should be FirstName and Email", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create nested dynamic objects asynchronously")]
        [Xunit.TraitAttribute("FeatureTitle", "AsyncSupport")]
        [Xunit.TraitAttribute("Description", "Create nested dynamic objects asynchronously")]
        public async System.Threading.Tasks.Task CreateNestedDynamicObjectsAsynchronously()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create nested dynamic objects asynchronously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Entity",
                            "Properties"});
                table5.AddRow(new string[] {
                            "User",
                            "{\"Name\": \"John\", \"Age\": 30, \"Email\": \"john@example.com\"}"});
                table5.AddRow(new string[] {
                            "Address",
                            "{\"Street\": \"Main St\", \"City\": \"New York\", \"ZipCode\": \"10001\"}"});
#line 44
        await testRunner.GivenAsync("I have a table with nested JSON data for async processing", ((string)(null)), table5, "Given ");
#line hidden
#line 48
        await testRunner.WhenAsync("I create a nested dynamic object asynchronously", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
        await testRunner.ThenAsync("the async User name should be John", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
        await testRunner.AndAsync("the async Address city should be New York", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AsyncSupportFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AsyncSupportFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
