name: Build and Package

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      
    - name: Set version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Set version for non-tagged builds
      if: "!startsWith(github.ref, 'refs/tags/v')"
      run: echo "VERSION=0.0.0-dev.$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${VERSION}
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Pack
      run: dotnet pack "ExecuteAutomation.Reqnroll.Dynamics/ExecuteAutomation.Reqnroll.Dynamics.csproj" --configuration Release --no-build --output nupkgs /p:Version=${VERSION}
    
    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: nupkgs/*.nupkg
    
    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: nupkgs/*.nupkg
        name: Release ${{ env.VERSION }}
        body: |
          Release of ExecuteAutomation.Reqnroll.Dynamics v${{ env.VERSION }}
          
          ## Changes in this release
          
          _Please add release notes manually_
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 