name: Reqnroll Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.cs'
      - '**.feature'
      - '**/*.csproj'
      - '.github/workflows/reqnroll-tests.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.cs'
      - '**.feature'
      - '**/*.csproj'
      - '.github/workflows/reqnroll-tests.yml'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

jobs:
  reqnroll-tests:
    name: Reqnroll Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          8.0.x
    
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.config', '**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Reqnroll tests
      run: dotnet test "ExecuteAutomation.Reqnroll.Dynamics.Specs/ExecuteAutomation.Reqnroll.Dynamics.Specs.csproj" --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Reqnroll Tests
        path: "TestResults/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
    
    - name: Generate Reqnroll Living Documentation
      if: success() || failure()
      run: |
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI || true
        livingdoc test-assembly "ExecuteAutomation.Reqnroll.Dynamics.Specs/bin/Release/net6.0/ExecuteAutomation.Reqnroll.Dynamics.Specs.dll" -t "ExecuteAutomation.Reqnroll.Dynamics.Specs/bin/Release/net6.0/TestExecution.json" --output "TestResults/LivingDoc.html"
      continue-on-error: true
    
    - name: Upload Reqnroll Living Documentation
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: reqnroll-living-doc
        path: TestResults/LivingDoc.html
        if-no-files-found: ignore 